MODEL_SIZE = "base"
RECORD_SECONDS = 3
AUDIO_FILE = "command.wav"

CONNECTION_STRING = ''
TAKEOFF_ALTITUDE = 2

DRUM_SERVO_CHANNEL = 10
ELECTROMAGNET_CHANNEL = 9

VELOCITY_X = 1.0  
VELOCITY_Y = 1.0  
VELOCITY_Z = 1.0  

YAW_RATE = 30
YAW_INCREMENT = 90

DRUM_INCREMENT = 90

MAGNET_ON_PWM = 2000
MAGNET_OFF_PWM = 1000