MODEL_SIZE = "base"
RECORD_SECONDS = 3
AUDIO_FILE = "command.wav"

PX4_MODE_OFFBOARD = 6 << 16

CONNECTION_STRING = "/dev/ttyUSB0" #wsl px4 sim (do not use 14550, QGC is using that)
BAUD_RATE = 57600

TAKEOFF_ALTITUDE = 1.0
DRUM_SERVO_CHANNEL = 10
ELECTROMAGNET_CHANNEL = 9

SPEED = 1.0
YAW_RATE = 30

DRUM_INCREMENT = 90

MAGNET_ON_PWM = 2000
MAGNET_OFF_PWM = 1000
